/**
 * 행동 정의.
 *
 * 요구사항서 5장(헌터) / 6장(성좌)의 행동을 모두 등록해 둔다.
 * `implementedIn` 이 현재 구현 단계(CURRENT_PHASE)보다 크면
 * UI 에는 표시되지만 선택할 수 없다 — 앞으로 열릴 행동을 숨기지 않기 위한 장치다.
 *
 * 캐릭터별 커스텀 스킬(Phase 2)은 이 목록을 대체하지 않고,
 * 같은 ActionDefinition 형태로 캐릭터 데이터에서 추가된다.
 */

import type { ActionDefinition } from '../types';

export const HUNTER_ACTIONS: ActionDefinition[] = [
  {
    id: 'hunter.wait',
    side: 'HUNTER',
    kind: 'WAIT',
    label: 'STANDBY',
    labelKo: '대기',
    description: '행동하지 않고 행동력을 아낀다.',
    apCost: 0,
    target: 'NONE',
    effect: {},
    implementedIn: 1,
  },
  {
    id: 'hunter.attack',
    side: 'HUNTER',
    kind: 'ATTACK',
    label: 'BASIC ATTACK',
    labelKo: '기본 공격',
    description: '무기로 적을 직접 공격한다.',
    apCost: 1,
    target: 'ENEMY',
    effect: { damage: 1 },
    implementedIn: 1,
  },
  {
    id: 'hunter.defend',
    side: 'HUNTER',
    kind: 'DEFENSE',
    label: 'GUARD',
    labelKo: '기본 방어',
    description: '이번 라운드에 받는 피해를 감소시킨다.',
    apCost: 1,
    target: 'SELF',
    effect: { damageReduction: 0.4 },
    implementedIn: 1,
  },
  {
    id: 'hunter.skill',
    side: 'HUNTER',
    kind: 'SKILL',
    label: 'SKILL',
    labelKo: '일반 스킬',
    description: '캐릭터별 커스텀 스킬을 사용한다.',
    apCost: 2,
    target: 'ENEMY',
    effect: { damage: 1.6 },
    implementedIn: 2,
  },
  {
    id: 'hunter.skill.heavy',
    side: 'HUNTER',
    kind: 'SKILL',
    label: 'HEAVY SKILL',
    labelKo: '강력한 스킬',
    description: '일반 스킬보다 강력한 효과를 가진다.',
    apCost: 3,
    target: 'ENEMY',
    effect: { damage: 2.4 },
    implementedIn: 2,
  },
  {
    id: 'hunter.protect',
    side: 'HUNTER',
    kind: 'PROTECT',
    label: 'PROTECT',
    labelKo: '보호',
    description: '지정한 페어의 헌터에게 피해 감소를 부여한다.',
    apCost: 2,
    target: 'ALLY',
    effect: { applyStatusIds: ['guard.up'], statusHolder: 'HUNTER' },
    implementedIn: 3,
  },
  {
    id: 'hunter.rescue',
    side: 'HUNTER',
    kind: 'RESCUE',
    label: 'RESCUE',
    labelKo: '구조',
    description: '전투 불능 상태의 헌터를 끌어내 되살린다.',
    apCost: 2,
    target: 'ALLY',
    effect: {},
    implementedIn: 3,
  },
  {
    id: 'hunter.gimmick',
    side: 'HUNTER',
    kind: 'GIMMICK',
    label: 'GIMMICK',
    labelKo: '기믹 수행',
    description: '층에 걸린 장치를 처리한다. 누적 수행 횟수로 해제된다.',
    apCost: 1,
    target: 'NONE',
    effect: {},
    implementedIn: 3,
  },
  {
    id: 'hunter.item',
    side: 'HUNTER',
    kind: 'ITEM',
    label: 'ITEM',
    labelKo: '아이템',
    description: '소지한 아이템을 사용한다. 비용은 아이템별로 다르다.',
    apCost: 1,
    target: 'PAIR',
    effect: {},
    implementedIn: 6,
  },
];

export const CONSTELLATION_ACTIONS: ActionDefinition[] = [
  {
    id: 'const.wait',
    side: 'CONSTELLATION',
    kind: 'WAIT',
    label: 'OBSERVE',
    labelKo: '관측',
    description: '개입하지 않고 전황을 지켜본다.',
    apCost: 0,
    target: 'NONE',
    effect: {},
    implementedIn: 1,
  },
  {
    id: 'const.buff',
    side: 'CONSTELLATION',
    kind: 'BUFF',
    label: 'BUFF',
    labelKo: '버프',
    description: '계약한 헌터의 공격력을 끌어올린다. (2 라운드 지속)',
    apCost: 1,
    target: 'PAIR',
    effect: { applyStatusIds: ['atk.up'] },
    implementedIn: 1,
  },
  {
    id: 'const.debuff',
    side: 'CONSTELLATION',
    kind: 'DEBUFF',
    label: 'DEBUFF',
    labelKo: '디버프',
    description: '적의 방어력을 깎는다. (2 라운드 지속 · 2 중첩)',
    apCost: 1,
    target: 'ENEMY',
    effect: { applyStatusIds: ['def.down'] },
    implementedIn: 1,
  },
  {
    id: 'const.revelation',
    side: 'CONSTELLATION',
    kind: 'REVELATION',
    label: 'REVELATION',
    labelKo: '계시',
    description: '적의 다음 패턴 정보를 헌터에게 내려준다.',
    apCost: 2,
    target: 'NONE',
    effect: { revealPattern: true },
    implementedIn: 1,
  },
  {
    id: 'const.buff.heavy',
    side: 'CONSTELLATION',
    kind: 'BUFF',
    label: 'GREATER BUFF',
    labelKo: '강력한 버프',
    description: '공격력을 크게 끌어올린다. (3 라운드 지속)',
    apCost: 2,
    target: 'PAIR',
    effect: { applyStatusIds: ['atk.up.great'] },
    implementedIn: 2,
  },
  {
    id: 'const.debuff.heavy',
    side: 'CONSTELLATION',
    kind: 'DEBUFF',
    label: 'GREATER DEBUFF',
    labelKo: '강력한 디버프',
    description: '방어를 무너뜨리고 약점을 드러낸다. (3 라운드 지속)',
    apCost: 2,
    target: 'ENEMY',
    effect: { applyStatusIds: ['def.down.great', 'weak'] },
    implementedIn: 2,
  },
  {
    id: 'const.manifest',
    side: 'CONSTELLATION',
    kind: 'MANIFEST',
    label: 'MANIFEST',
    labelKo: '부분 현신',
    description: '권능의 일부를 전장에 직접 구현한다. 전투당 사용 횟수가 제한된다.',
    apCost: 3,
    target: 'ENEMY',
    effect: { damage: 2 },
    implementedIn: 3,
  },
  {
    id: 'const.manifest.full',
    side: 'CONSTELLATION',
    kind: 'FULL_MANIFEST',
    label: 'FULL MANIFEST',
    labelKo: '완전 현신',
    description: '성좌가 직접 전장에 개입한다. 공략 단위로 사용 횟수가 제한된다.',
    apCost: 5,
    target: 'ENEMY',
    effect: { damage: 4 },
    implementedIn: 3,
  },
  {
    id: 'const.relic',
    side: 'CONSTELLATION',
    kind: 'ITEM',
    label: 'RELIC',
    labelKo: '성유물',
    description: '성좌 전용 성유물 또는 공용 아이템을 사용한다.',
    apCost: 1,
    target: 'PAIR',
    effect: {},
    implementedIn: 6,
  },
];

export const ALL_ACTIONS: ActionDefinition[] = [...HUNTER_ACTIONS, ...CONSTELLATION_ACTIONS];

export function findAction(id: string | null): ActionDefinition | null {
  if (!id) return null;
  return ALL_ACTIONS.find((action) => action.id === id) ?? null;
}
